#!/bin/bash

DOC_VERSION="$1"
CWD="$2"
PWD=$(pwd)

cd "$CWD"
sudo apt-get update
sudo apt-get -y install python-pip
sudo pip install sphinx
sudo pip install sphinx_rtd_theme
sudo apt-get -y install subversion
sudo svn export https://github.com/jeff1evesque/machine-learning/trunk/doc source

if [ "$CWD" != 'vagrant' ]
then
    rm -f latest
fi

rm -rf "$DOC_VERSION"
mkdir -p source/_static
make html
mv -f html build
cp -rf build "$DOC_VERSION"
rm -rf build source/html doctrees

if [ "$CWD" != 'vagrant' ]
then
    ln -s "DOC_VERSION" latest
fi

cd "$PWD"
